version: '3.8' 

services:
  db:
    image: postgres:13-alpine
    container_name: simplebank
    environment:
      - POSTGRES_USER=simplebank
      - POSTGRES_PASSWORD=simplebank 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: